# Generated by Django 4.2.1 on 2023-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0002_document_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
