# Generated by Django 4.2.1 on 2023-06-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0003_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
