# Generated by Django 4.2.1 on 2023-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0005_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_list',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
