# Generated by Django 4.2.1 on 2023-07-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0008_alter_skills_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_skills', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FileUpload.skills')),
            ],
        ),
    ]
