# Generated by Django 4.2.1 on 2023-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0009_jobrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrec',
            name='job_recs',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
